services:
  db:
    image: postgres:16.4-alpine3.20
    restart: always
    environment:
      POSTGRES_DB: dd_parser
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  minio:
    image: quay.io/minio/minio:RELEASE.2024-08-26T15-33-07Z
    restart: always
    command:
      - server
      - /data
      - --console-address
      - :9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    ports:
      - 9000:9000
      - 9001:9001
